# include:
include:
  - board: nice_nano_v2
    shield: debug_test
  - board: nice_nano_v2
    shield: kyria_left
  - board: nice_nano_v2
    shield: kyria_right
  - board: nice_nano_v2
    shield: try_02_left nice_view_adapter nice_view_gem
  - board: nice_nano_v2
    shield: try_02_right nice_view
