include:
  - board: nice_nano@2
    shield: chocofi_left
    # shield: chocofi_left nice_view_adapter nice_view_gem
  - board: nice_nano@2
    # shield: chocofi_right nice_view_adapter nice_view_gem
    shield: chocofi_right
